### ISSUE TITLE
#US06 #TK07: Implementación del Carrito de Compras(Procesamiento de pago)

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoBackend#17]
#TK07 (deriva de #US06)
#15 

_Backend - Procesamiento de Pago:_

- Implementar endpoint en Django para simular procesamiento de pago.
- Validar datos de pago y actualizar estado de la compra en la base de datos.

**Comment by nahir1009** [comment]
se uso la api de mercado pago
