### ISSUE TITLE
#TS01: Funcionalidades: documentación bbdd

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoBackend#2]
#TS01

_Descripción:_
Base de Datos: Crear una carpeta de documentación en el proyecto, donde se adjuntarán los documentos pertinentes en el backend.
Adjuntar el modelo conceptual y el modelo lógico de la base de datos.

_Criterio de aceptación:_

Logra actualizar el modelo conceptual (DER) y el modelo lógico de datos a utilizar.

Esta task deriva de la Historia de Usuario: #6

**Comment by VirginiaFalconi** [comment]
Cierro issue, tiene un error pero no logre solucionarlo. Lo dejare para el proximo sprint.
