### ISSUE TITLE
#US01: Crear carpeta de documentación y adjuntar modelos de base de datos

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoBackend#6]
_Descripción:_
Como desarrolladores del proyecto, necesitamos una carpeta de documentación en el backend del proyecto donde podamos adjuntar los documentos pertinentes, incluyendo el modelo conceptual (DER) y el modelo lógico de la base de datos.

_Criterios de aceptación:_

1. Se debe crear una carpeta de documentación en el proyecto.
2. La carpeta de documentación debe estar ubicada en el backend.
3. Se deben adjuntar correctamente los documentos pertinentes, incluyendo el modelo conceptual (DER) y el modelo lógico de la base de datos.
4. Los modelos de base de datos adjuntos deben estar actualizados y reflejar los cambios realizados en la estructura de la base de datos.

**Comment by VirginiaFalconi** [comment]
No se agregaron tablas a la base de datos, luego se evaluara si es necesario y se completaran para el próximo sprint.
